### PR TITLE
Adding .gitignore, install instructions, and setting report every 1000 evt

### PR DESCRIPTION
**Pull request by alexAubin**
Hi Kirill,

I had some troubles setting up the EGamma files so I'd like to add the install instructions for other people. I'm also proposing adding *.pyc in the .gitignore and having the evt id report in the log every 1000.

Cheers !

Alex

### CODE REVIEW

**Comment by MichaelButtignol** [comment]
Moi, ze veux des sossures...

**Comment by alexAubin** [comment]
Hi,

I added some cleaning and refactorized some part such as the booking of TMVA readers

Cheers !

Alex

**Comment by kskovpen** [comment]
Hi Alex, have you included these updates into your pull request ? I think you have already merged it with the master ... I would like to ask to avoid doing that.

**Comment by alexAubin** [comment]
Ugh sorry I just realized I clicked on merge instead of comment in the rush :/

**Comment by kskovpen** [comment]
OK. Thanks for the update. Don't forget to checkout the latest changes each time from the master (I just did a tiny commit).

**Comment by alexAubin** [comment]
Hey Kirill,

after investigating what happened, I realized I both mistakenly clicked on merge here and thought I pushed the other commit c17b241 only to the oneLeptonStop fork, but my `git push` pushed it to the default remote which was the IPHC one. Sorry about that, it won't happen again :s.

**Comment by kskovpen** [comment]
Hi Alex. No problem, does the master version reflects your latest changes so that I can work from that ?

**Comment by alexAubin** [comment]
Hi Kirill,

yes, that's my latest changes. To answer one of your email, I still haven't made a tag because I'm checking if there are some info missing for the phys14 study I made. Also Thibaut has a PR on the way from his optimization studies with Eric regarding buffer and compression but we'll discuss this in another thread I guess.

Cheers !

Alex

**Comment by kskovpen** [comment]
OK, thanks for the info. Then I will add some more of the requested variables this week-end.

**Pull request merged**
